name: Aquasave Web

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: aquasave/aquasave@v1

      - name: Install dependencies
        run: dart pub get


